import ThemeSwitcher from "@/components/theme-switcher";
import FacebookSDK from "@/lib/FaceSdk";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-big-calendar/lib/css/react-big-calendar.css";
import "react-loading-skeleton/dist/skeleton.css";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import QueryClientProvider from "./QueryClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId="767357925688-m0cj63gqp1evmf0qj0e73m3oh1t629mu.apps.googleusercontent.com">
          <QueryClientProvider>
            <FacebookSDK />
            <ThemeSwitcher />
            <ReactQueryDevtools />
            <main>{children}</main>
          </QueryClientProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
